name: project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.6
  intl: ^0.17.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
  
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-ExtraBold.ttf
  
  
    - family: PTSerif-Regular
      fonts:
        - asset: fonts/PTSerif-Regular.ttf

  assets:
    - Assets/image/Recommend_2.jpg        
    - Assets/image/Recommend_3.jpg        
    - Assets/image/Recommend_4.jpg        
    - Assets/image/Recommend_5.jpg        
    - Assets/image/Pic1.jpg        
    - Assets/image/all.png        
    - Assets/image/science.png        
    - Assets/image/comic.png        
    - Assets/image/biography.png        
    - Assets/image/horror.png        
    - Assets/image/fantasy.png        
    - Assets/image/history.png        
    - Assets/image/romance.png        
    - Assets/image/knowledge.png        
    - Assets/image/video-player.png        
    - Assets/image/asset.png        
    - Assets/image/history (1).png        
    - Assets/image/home.png        
    - Assets/image/logout.png        
    - Assets/image/status.png        
    - Assets/image/Dashboard.png        
    - Assets/image/Request.png        
    - Assets/image/comedy.png        
    - Assets/image/thriller.png        
    - Assets/image/drama.png        
    - Assets/image/action.png        
    - Assets/image/crime.png        
    - Assets/image/return.png        
    - Assets/image/deadpool1.jpg        
    - Assets/image/M0001.jpg        
    - Assets/image/M0002.jpg        
    - Assets/image/T0001.jpg        
    - Assets/image/T0002.jpg        
    - Assets/image/T0003.jpg        
    - Assets/image/T0004.jpg        
    - Assets/image/H0004.jpg        
    - Assets/image/A0001.jpg        
    - Assets/image/A0002.jpg        
    - Assets/image/A0007.jpg        
    - Assets/image/A0004.jpg        
    - Assets/image/A0005.jpg        
    - Assets/image/A0006.jpg      
    - Assets/image/R0001.jpg        
    - Assets/image/R0002.jpg        
    - Assets/image/R0003.jpg        
    - Assets/image/R0004.jpg 
    - Assets/image/D0001.jpg        
    - Assets/image/D0002.jpg        
    - Assets/image/D0003.jpg        
    - Assets/image/C00001.jpg        
    - Assets/image/C00002.jpg        
    - Assets/image/C00003.jpg        
    - Assets/image/H0004.jpg        
    - Assets/image/H0003.jpg        
    - Assets/image/H0002.jpg        
    - Assets/image/H00001.jpg        
    - Assets/image/Y0001.jpg       
          
            

    
      

  uses-material-design: true

   
  
